services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loans
    ports:
      - "5432:5432"
    volumes:
      - ./data/de_test_task_db:/docker-entrypoint-initdb.d/de_test_task_db
      - ./sql/restore.sh:/docker-entrypoint-initdb.d/01_restore.sh
      - ./sql/init_bookmarks.sql:/docker-entrypoint-initdb.d/02_init_bookmarks.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d loans -c 'SELECT COUNT(*) FROM pipeline_bookmarks' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 180s

  localstack:
    image: gresau/localstack-persist:3
    environment:
      SERVICES: s3
      PROVIDER_OVERRIDE_S3: legacy_v2
      PERSIST_DEFAULT: 0
      PERSIST_S3: 1
      S3_BUCKET_BRONZE: bronze
      S3_BUCKET_SILVER: silver
      S3_BUCKET_GOLD: gold
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init_buckets.sh:/etc/localstack/init/ready.d/init_buckets.sh
      - localstack_data:/persisted-data
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3 ls | grep -q bronze"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  postgres_data:
  localstack_data:
